feat/front-renewal
yatabis/kassen_reversi pull request #2
Opened 2022-08-07 08:24 UTC by matsu7089

## 概要

フロントのコードをリニューアルしました :tada:

## 主な変更点

- yarnプロジェクトファイルの追加
- 新しいフロントのコードを追加
- index.htmlの更新と不要になったファイルの削除
- READMEファイルの追加

## 共有事項

- 現段階のフロント機能は全部用意したはず！
- 色々ファイル増やしてしまったのでプロジェクトファイルの置き方に違和感ないか一応確認お願いします！

2022-08-07 12:17 UTC, yatabis commented
@matsu7089 
ご対応ありがとうございます！
まだコード見れていないですが、実行しようとして `yarn build` すると以下のエラーが発生するのですが何か対応ありますでしょうか？（`yarn dev` は問題なく動作していそうです）
おそらく BigInt あたりかなと思っていますが。。
ご確認お願いいたします 🙇 
```
🚨  /Users/shin/Desktop/Projects/kassen_reversi/front/display/ReversiBoard.js: Unexpected token name «n», expected punc «;»
    at Z.get (/Users/shin/Desktop/Projects/kassen_reversi/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (/Users/shin/Desktop/Projects/kassen_reversi/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (/Users/shin/Desktop/Projects/kassen_reversi/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (/Users/shin/Desktop/Projects/kassen_reversi/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Bundler.loadAsset (/Users/shin/Desktop/Projects/kassen_reversi/node_modules/parcel-bundler/src/Bundler.js:577:19)
    at async /Users/shin/Desktop/Projects/kassen_reversi/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 1)
    at async Bundler.loadAsset (/Users/shin/Desktop/Projects/kassen_reversi/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /Users/shin/Desktop/Projects/kassen_reversi/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 3)
```

2022-08-07 12:27 UTC, yatabis requested changes
1点だけご確認お願いいたします 🙇

2022-08-07 12:27 UTC, yatabis commented on README.md
> +# kassen_reversi
ありがとうございます 👍

2022-08-07 12:27 UTC, yatabis commented on assets/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
このあたり Google Fonts のためのものなので、使わないのであれば削除していただければと思います

2022-08-09 00:07 UTC, matsu7089 commented
バンドラとして使っていた parcel のバージョンが古いものだったのでアップグレードしました
ビルドできるようになったので、再確認お願いします！ 🙏

2022-08-09 00:54 UTC, yatabis approved these changes
ご対応ありがとうございます！
![lgtm](https://image.lgtmoon.dev/176803)

2022-08-09 08:45 UTC, merged